dist: bionic
env:
  global:
    - IUP_DL='https://sourceforge.net/projects/iup/files/3.29/Linux%20Libraries/iup-3.29_Linux415_64_lib.tar.gz'

language: rust

install:
  # Download and install IUP
  - mkdir iup_libs/
  - wget $IUP_DL -O iup_libs.tar.gz
  - tar -xzvf iup_libs.tar.gz -C iup_libs/
  # By piping a newline to ./install, we skip the enter prompt
  - (cd iup_libs/ && echo -ne '\n' | sudo ./install)
  - sudo cp iup_libs/ftgl/lib/Linux415_64/libftgl.so /usr/lib/
  - sudo ldconfig
  - rm -rf iup_libs/

script:
  - cargo build -v
  - cargo test -v
